Reproduce for bug in https://github.com/actions/setup-python/pull/1128.
